KCONFIG_DEFCONFIG := qemu_virt28_defconfig

include arch/arm/board-qemu-virt28/Makefile

x15_SOURCES-y += \
        arch/arm/machine/boot_asm.S \
        arch/arm/machine/boot.c \
        arch/arm/machine/cpu.c \
        arch/arm/machine/pmap.c \
        arch/arm/machine/ssp.c \
        arch/arm/machine/strace.c \
        arch/arm/machine/tcb_asm.S \
        arch/arm/machine/tcb.c
